### ISSUE TITLE
Vinculación de Versiones

### ISSUE THREAD

**Issue by vicenteguardiola** [zapic0/deployer#3]
Hola,

Acabo de echar un vistazo al plugin y me parece muy interesante y útil. Sin embargo, me pregunto si a un Deploy puede vincularse una versión.

Nosotros usamos versiones para agrupar tickets y tener así control de qué se ha desplegado, pero la idea de usar el plugin Deployer para controlar cuándo me gusta.

¿Es posible vincular versiones ¿Lo tienes previsto?

Gracias

**Comment by zapic0** [comment]
Hola:

No suelo utilizar versiones, pero con tu sugerencia parece un paso **evidente**.

Me pongo con ello en cuanto pueda, muchas gracias!!!

**Comment by zapic0** [comment]
Ya está añadido.

Muchas gracias por la sugerencia.

**Comment by vicenteguardiola** [comment]
Muchas gracias a ti por tu aportación
