### ISSUE TITLE
Deployer uninstall

### ISSUE THREAD

**Issue by gnovelli** [zapic0/deployer#6]
Hello,
I have tried your plugin. It's fine. At the moment I want to disable it.
I have tried uninstalling but uninstall seems incomplete: Deploys tab continues to be shown and of course is unusable (complete uninstall process with migrate to VERSION 0 and removal of deployer directory under plugins directory).
Another reason that I have to uninstall it is that, as previously stated by you in another issue, the Deploys tab is visible in a project even if is not set in the project. This behaviour could be fine for some requirements but isn't fine in other requirements like different modules per project and deploys visible only on some projects.

Could you give me an hint?

Best regards,
Giovanni

**Comment by zapic0** [comment]
Hi @gnovelli, please try running migration to version 0:
`bundle exec rake redmine:plugins:migrate NAME=deployer VERSION=0 RAILS_ENV=production`

Then remove plugin from your plugins folder.

**Comment by gnovelli** [comment]
It's fine. Just something gone wrong at first try. Now it's ok. 
Thanks @zapic0
